# Configuration Settings for ZED-F9K device

debug: 1                    # Range 0-4 (0 means no debug statements will print)

device: /dev/ttyACM0
frame_id: gps

uart1:
  baudrate: 115200

rate: 1
nav_rate: 1

gnss:
  gps: true
  glonass: true      
  beidou: true
  galileo: true           
  qzss: true

# Enable u-blox message publishers
publish:
  all: false
  aid:
    eph: true
  nav:
    all: true
    relposned: true
    posllh: true
    posecef: true
    pvt: true
  esf:
    alg: false
    ins: true
    meas: true

